/* soapH.h
   Generated by gSOAP 2.7.12 from testws.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_ns2__isUserValidated
#define SOAP_TYPE_ns2__isUserValidated (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__isUserValidated(struct soap*, struct ns2__isUserValidated *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__isUserValidated(struct soap*, const struct ns2__isUserValidated *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__isUserValidated(struct soap*, const struct ns2__isUserValidated *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__isUserValidated(struct soap*, const char*, int, const struct ns2__isUserValidated *, const char*);
SOAP_FMAC3 struct ns2__isUserValidated * SOAP_FMAC4 soap_get_ns2__isUserValidated(struct soap*, struct ns2__isUserValidated *, const char*, const char*);
SOAP_FMAC3 struct ns2__isUserValidated * SOAP_FMAC4 soap_in_ns2__isUserValidated(struct soap*, const char*, struct ns2__isUserValidated *, const char*);

#ifndef SOAP_TYPE_ns2__isUserValidatedResponse
#define SOAP_TYPE_ns2__isUserValidatedResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__isUserValidatedResponse(struct soap*, struct ns2__isUserValidatedResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__isUserValidatedResponse(struct soap*, const struct ns2__isUserValidatedResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__isUserValidatedResponse(struct soap*, const struct ns2__isUserValidatedResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__isUserValidatedResponse(struct soap*, const char*, int, const struct ns2__isUserValidatedResponse *, const char*);
SOAP_FMAC3 struct ns2__isUserValidatedResponse * SOAP_FMAC4 soap_get_ns2__isUserValidatedResponse(struct soap*, struct ns2__isUserValidatedResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__isUserValidatedResponse * SOAP_FMAC4 soap_in_ns2__isUserValidatedResponse(struct soap*, const char*, struct ns2__isUserValidatedResponse *, const char*);

#ifndef SOAP_TYPE_ns2__getDynaTuneInfo
#define SOAP_TYPE_ns2__getDynaTuneInfo (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getDynaTuneInfo(struct soap*, struct ns2__getDynaTuneInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getDynaTuneInfo(struct soap*, const struct ns2__getDynaTuneInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getDynaTuneInfo(struct soap*, const struct ns2__getDynaTuneInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getDynaTuneInfo(struct soap*, const char*, int, const struct ns2__getDynaTuneInfo *, const char*);
SOAP_FMAC3 struct ns2__getDynaTuneInfo * SOAP_FMAC4 soap_get_ns2__getDynaTuneInfo(struct soap*, struct ns2__getDynaTuneInfo *, const char*, const char*);
SOAP_FMAC3 struct ns2__getDynaTuneInfo * SOAP_FMAC4 soap_in_ns2__getDynaTuneInfo(struct soap*, const char*, struct ns2__getDynaTuneInfo *, const char*);

#ifndef SOAP_TYPE_ns2__getDynaTuneInfoResponse
#define SOAP_TYPE_ns2__getDynaTuneInfoResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getDynaTuneInfoResponse(struct soap*, struct ns2__getDynaTuneInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getDynaTuneInfoResponse(struct soap*, const struct ns2__getDynaTuneInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getDynaTuneInfoResponse(struct soap*, const struct ns2__getDynaTuneInfoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getDynaTuneInfoResponse(struct soap*, const char*, int, const struct ns2__getDynaTuneInfoResponse *, const char*);
SOAP_FMAC3 struct ns2__getDynaTuneInfoResponse * SOAP_FMAC4 soap_get_ns2__getDynaTuneInfoResponse(struct soap*, struct ns2__getDynaTuneInfoResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getDynaTuneInfoResponse * SOAP_FMAC4 soap_in_ns2__getDynaTuneInfoResponse(struct soap*, const char*, struct ns2__getDynaTuneInfoResponse *, const char*);

#ifndef SOAP_TYPE_ns2__validateUser
#define SOAP_TYPE_ns2__validateUser (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__validateUser(struct soap*, struct ns2__validateUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__validateUser(struct soap*, const struct ns2__validateUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__validateUser(struct soap*, const struct ns2__validateUser *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__validateUser(struct soap*, const char*, int, const struct ns2__validateUser *, const char*);
SOAP_FMAC3 struct ns2__validateUser * SOAP_FMAC4 soap_get_ns2__validateUser(struct soap*, struct ns2__validateUser *, const char*, const char*);
SOAP_FMAC3 struct ns2__validateUser * SOAP_FMAC4 soap_in_ns2__validateUser(struct soap*, const char*, struct ns2__validateUser *, const char*);

#ifndef SOAP_TYPE_ns2__validateUserResponse
#define SOAP_TYPE_ns2__validateUserResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__validateUserResponse(struct soap*, struct ns2__validateUserResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__validateUserResponse(struct soap*, const struct ns2__validateUserResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__validateUserResponse(struct soap*, const struct ns2__validateUserResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__validateUserResponse(struct soap*, const char*, int, const struct ns2__validateUserResponse *, const char*);
SOAP_FMAC3 struct ns2__validateUserResponse * SOAP_FMAC4 soap_get_ns2__validateUserResponse(struct soap*, struct ns2__validateUserResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__validateUserResponse * SOAP_FMAC4 soap_in_ns2__validateUserResponse(struct soap*, const char*, struct ns2__validateUserResponse *, const char*);

#ifndef SOAP_TYPE_ns2__createNewUser
#define SOAP_TYPE_ns2__createNewUser (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__createNewUser(struct soap*, struct ns2__createNewUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__createNewUser(struct soap*, const struct ns2__createNewUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__createNewUser(struct soap*, const struct ns2__createNewUser *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__createNewUser(struct soap*, const char*, int, const struct ns2__createNewUser *, const char*);
SOAP_FMAC3 struct ns2__createNewUser * SOAP_FMAC4 soap_get_ns2__createNewUser(struct soap*, struct ns2__createNewUser *, const char*, const char*);
SOAP_FMAC3 struct ns2__createNewUser * SOAP_FMAC4 soap_in_ns2__createNewUser(struct soap*, const char*, struct ns2__createNewUser *, const char*);

#ifndef SOAP_TYPE_ns2__createNewUserResponse
#define SOAP_TYPE_ns2__createNewUserResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__createNewUserResponse(struct soap*, struct ns2__createNewUserResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__createNewUserResponse(struct soap*, const struct ns2__createNewUserResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__createNewUserResponse(struct soap*, const struct ns2__createNewUserResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__createNewUserResponse(struct soap*, const char*, int, const struct ns2__createNewUserResponse *, const char*);
SOAP_FMAC3 struct ns2__createNewUserResponse * SOAP_FMAC4 soap_get_ns2__createNewUserResponse(struct soap*, struct ns2__createNewUserResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__createNewUserResponse * SOAP_FMAC4 soap_in_ns2__createNewUserResponse(struct soap*, const char*, struct ns2__createNewUserResponse *, const char*);

#ifndef SOAP_TYPE_ns2__testWebService
#define SOAP_TYPE_ns2__testWebService (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__testWebService(struct soap*, struct ns2__testWebService *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__testWebService(struct soap*, const struct ns2__testWebService *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__testWebService(struct soap*, const struct ns2__testWebService *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__testWebService(struct soap*, const char*, int, const struct ns2__testWebService *, const char*);
SOAP_FMAC3 struct ns2__testWebService * SOAP_FMAC4 soap_get_ns2__testWebService(struct soap*, struct ns2__testWebService *, const char*, const char*);
SOAP_FMAC3 struct ns2__testWebService * SOAP_FMAC4 soap_in_ns2__testWebService(struct soap*, const char*, struct ns2__testWebService *, const char*);

#ifndef SOAP_TYPE_ns2__testWebServiceResponse
#define SOAP_TYPE_ns2__testWebServiceResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__testWebServiceResponse(struct soap*, struct ns2__testWebServiceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__testWebServiceResponse(struct soap*, const struct ns2__testWebServiceResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__testWebServiceResponse(struct soap*, const struct ns2__testWebServiceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__testWebServiceResponse(struct soap*, const char*, int, const struct ns2__testWebServiceResponse *, const char*);
SOAP_FMAC3 struct ns2__testWebServiceResponse * SOAP_FMAC4 soap_get_ns2__testWebServiceResponse(struct soap*, struct ns2__testWebServiceResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__testWebServiceResponse * SOAP_FMAC4 soap_in_ns2__testWebServiceResponse(struct soap*, const char*, struct ns2__testWebServiceResponse *, const char*);

#ifndef SOAP_TYPE_ns2__isConnected
#define SOAP_TYPE_ns2__isConnected (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__isConnected(struct soap*, struct ns2__isConnected *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__isConnected(struct soap*, const struct ns2__isConnected *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__isConnected(struct soap*, const struct ns2__isConnected *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__isConnected(struct soap*, const char*, int, const struct ns2__isConnected *, const char*);
SOAP_FMAC3 struct ns2__isConnected * SOAP_FMAC4 soap_get_ns2__isConnected(struct soap*, struct ns2__isConnected *, const char*, const char*);
SOAP_FMAC3 struct ns2__isConnected * SOAP_FMAC4 soap_in_ns2__isConnected(struct soap*, const char*, struct ns2__isConnected *, const char*);

#ifndef SOAP_TYPE_ns2__isConnectedResponse
#define SOAP_TYPE_ns2__isConnectedResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__isConnectedResponse(struct soap*, struct ns2__isConnectedResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__isConnectedResponse(struct soap*, const struct ns2__isConnectedResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__isConnectedResponse(struct soap*, const struct ns2__isConnectedResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__isConnectedResponse(struct soap*, const char*, int, const struct ns2__isConnectedResponse *, const char*);
SOAP_FMAC3 struct ns2__isConnectedResponse * SOAP_FMAC4 soap_get_ns2__isConnectedResponse(struct soap*, struct ns2__isConnectedResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__isConnectedResponse * SOAP_FMAC4 soap_in_ns2__isConnectedResponse(struct soap*, const char*, struct ns2__isConnectedResponse *, const char*);

#ifndef SOAP_TYPE__Struct_1
#define SOAP_TYPE__Struct_1 (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Struct_1(struct soap*, struct _Struct_1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__Struct_1(struct soap*, struct _Struct_1 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__Struct_1(struct soap*, const struct _Struct_1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Struct_1(struct soap*, const char*, int, const struct _Struct_1 *, const char*);
SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_get__Struct_1(struct soap*, struct _Struct_1 *, const char*, const char*);
SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_in__Struct_1(struct soap*, const char*, struct _Struct_1 *, const char*);

#ifndef SOAP_TYPE_ArrayOfArrayOf_USCORExsd_USCOREstring
#define SOAP_TYPE_ArrayOfArrayOf_USCORExsd_USCOREstring (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOfArrayOf_USCORExsd_USCOREstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOfArrayOf_USCORExsd_USCOREstring const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, const struct ArrayOfArrayOf_USCORExsd_USCOREstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, int, const struct ArrayOfArrayOf_USCORExsd_USCOREstring *, const char*);
SOAP_FMAC3 struct ArrayOfArrayOf_USCORExsd_USCOREstring * SOAP_FMAC4 soap_get_ArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOfArrayOf_USCORExsd_USCOREstring *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfArrayOf_USCORExsd_USCOREstring * SOAP_FMAC4 soap_in_ArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, struct ArrayOfArrayOf_USCORExsd_USCOREstring *, const char*);

#ifndef SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring
#define SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOf_USCORExsd_USCOREstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOf_USCORExsd_USCOREstring const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOf_USCORExsd_USCOREstring(struct soap*, const struct ArrayOf_USCORExsd_USCOREstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, int, const struct ArrayOf_USCORExsd_USCOREstring *, const char*);
SOAP_FMAC3 struct ArrayOf_USCORExsd_USCOREstring * SOAP_FMAC4 soap_get_ArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOf_USCORExsd_USCOREstring *, const char*, const char*);
SOAP_FMAC3 struct ArrayOf_USCORExsd_USCOREstring * SOAP_FMAC4 soap_in_ArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, struct ArrayOf_USCORExsd_USCOREstring *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons2__getDynaTuneInfoResponse
#define SOAP_TYPE_PointerTons2__getDynaTuneInfoResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getDynaTuneInfoResponse(struct soap*, struct ns2__getDynaTuneInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getDynaTuneInfoResponse(struct soap*, struct ns2__getDynaTuneInfoResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getDynaTuneInfoResponse(struct soap*, const char *, int, struct ns2__getDynaTuneInfoResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getDynaTuneInfoResponse ** SOAP_FMAC4 soap_get_PointerTons2__getDynaTuneInfoResponse(struct soap*, struct ns2__getDynaTuneInfoResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__getDynaTuneInfoResponse ** SOAP_FMAC4 soap_in_PointerTons2__getDynaTuneInfoResponse(struct soap*, const char*, struct ns2__getDynaTuneInfoResponse **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfArrayOf_USCORExsd_USCOREstring
#define SOAP_TYPE_PointerToArrayOfArrayOf_USCORExsd_USCOREstring (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOfArrayOf_USCORExsd_USCOREstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOfArrayOf_USCORExsd_USCOREstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, const char *, int, struct ArrayOfArrayOf_USCORExsd_USCOREstring *const*, const char *);
SOAP_FMAC3 struct ArrayOfArrayOf_USCORExsd_USCOREstring ** SOAP_FMAC4 soap_get_PointerToArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOfArrayOf_USCORExsd_USCOREstring **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfArrayOf_USCORExsd_USCOREstring ** SOAP_FMAC4 soap_in_PointerToArrayOfArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, struct ArrayOfArrayOf_USCORExsd_USCOREstring **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOf_USCORExsd_USCOREstring
#define SOAP_TYPE_PointerToArrayOf_USCORExsd_USCOREstring (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOf_USCORExsd_USCOREstring *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOf_USCORExsd_USCOREstring *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, const char *, int, struct ArrayOf_USCORExsd_USCOREstring *const*, const char *);
SOAP_FMAC3 struct ArrayOf_USCORExsd_USCOREstring ** SOAP_FMAC4 soap_get_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, struct ArrayOf_USCORExsd_USCOREstring **, const char*, const char*);
SOAP_FMAC3 struct ArrayOf_USCORExsd_USCOREstring ** SOAP_FMAC4 soap_in_PointerToArrayOf_USCORExsd_USCOREstring(struct soap*, const char*, struct ArrayOf_USCORExsd_USCOREstring **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__boolean
#define SOAP_TYPE_PointerToxsd__boolean (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__boolean(struct soap*, const char *, int, enum xsd__boolean *const*, const char *);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_get_PointerToxsd__boolean(struct soap*, enum xsd__boolean **, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_in_PointerToxsd__boolean(struct soap*, const char*, enum xsd__boolean **, const char*);

#ifndef SOAP_TYPE_PointerTo_Struct_1
#define SOAP_TYPE_PointerTo_Struct_1 (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_Struct_1(struct soap*, struct _Struct_1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_Struct_1(struct soap*, struct _Struct_1 *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_Struct_1(struct soap*, const char *, int, struct _Struct_1 *const*, const char *);
SOAP_FMAC3 struct _Struct_1 ** SOAP_FMAC4 soap_get_PointerTo_Struct_1(struct soap*, struct _Struct_1 **, const char*, const char*);
SOAP_FMAC3 struct _Struct_1 ** SOAP_FMAC4 soap_in_PointerTo_Struct_1(struct soap*, const char*, struct _Struct_1 **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
