/* soapClient.c
   Generated by gSOAP 2.7.12 from testws.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.12 2008-12-01 11:35:45 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__isConnected(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_gu, enum xsd__boolean *_isConnectedReturn)
{	struct ns2__isConnected soap_tmp_ns2__isConnected;
	struct ns2__isConnectedResponse *soap_tmp_ns2__isConnectedResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8081/authws/services/AuthenticationService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__isConnected._gu = _gu;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__isConnected(soap, &soap_tmp_ns2__isConnected);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__isConnected(soap, &soap_tmp_ns2__isConnected, "ns2:isConnected", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__isConnected(soap, &soap_tmp_ns2__isConnected, "ns2:isConnected", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_isConnectedReturn)
		return soap_closesock(soap);
	soap_default_xsd__boolean(soap, _isConnectedReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns2__isConnectedResponse = soap_get_ns2__isConnectedResponse(soap, NULL, "ns2:isConnectedResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_isConnectedReturn && soap_tmp_ns2__isConnectedResponse->_isConnectedReturn)
		*_isConnectedReturn = *soap_tmp_ns2__isConnectedResponse->_isConnectedReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__testWebService(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **testWebServiceReturn)
{	struct ns2__testWebService soap_tmp_ns2__testWebService;
	struct ns2__testWebServiceResponse *soap_tmp_ns2__testWebServiceResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8081/authws/services/AuthenticationService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__testWebService(soap, &soap_tmp_ns2__testWebService);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__testWebService(soap, &soap_tmp_ns2__testWebService, "ns2:testWebService", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__testWebService(soap, &soap_tmp_ns2__testWebService, "ns2:testWebService", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!testWebServiceReturn)
		return soap_closesock(soap);
	*testWebServiceReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns2__testWebServiceResponse = soap_get_ns2__testWebServiceResponse(soap, NULL, "ns2:testWebServiceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (testWebServiceReturn && soap_tmp_ns2__testWebServiceResponse->testWebServiceReturn)
		*testWebServiceReturn = *soap_tmp_ns2__testWebServiceResponse->testWebServiceReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__createNewUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ArrayOf_USCORExsd_USCOREstring *_params, char **_createNewUserReturn)
{	struct ns2__createNewUser soap_tmp_ns2__createNewUser;
	struct ns2__createNewUserResponse *soap_tmp_ns2__createNewUserResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8081/authws/services/AuthenticationService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__createNewUser._params = _params;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__createNewUser(soap, &soap_tmp_ns2__createNewUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__createNewUser(soap, &soap_tmp_ns2__createNewUser, "ns2:createNewUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__createNewUser(soap, &soap_tmp_ns2__createNewUser, "ns2:createNewUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_createNewUserReturn)
		return soap_closesock(soap);
	*_createNewUserReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns2__createNewUserResponse = soap_get_ns2__createNewUserResponse(soap, NULL, "ns2:createNewUserResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_createNewUserReturn && soap_tmp_ns2__createNewUserResponse->_createNewUserReturn)
		*_createNewUserReturn = *soap_tmp_ns2__createNewUserResponse->_createNewUserReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__validateUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ArrayOf_USCORExsd_USCOREstring *_params, char **_validateUserReturn)
{	struct ns2__validateUser soap_tmp_ns2__validateUser;
	struct ns2__validateUserResponse *soap_tmp_ns2__validateUserResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8081/authws/services/AuthenticationService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__validateUser._params = _params;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__validateUser(soap, &soap_tmp_ns2__validateUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__validateUser(soap, &soap_tmp_ns2__validateUser, "ns2:validateUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__validateUser(soap, &soap_tmp_ns2__validateUser, "ns2:validateUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_validateUserReturn)
		return soap_closesock(soap);
	*_validateUserReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns2__validateUserResponse = soap_get_ns2__validateUserResponse(soap, NULL, "ns2:validateUserResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_validateUserReturn && soap_tmp_ns2__validateUserResponse->_validateUserReturn)
		*_validateUserReturn = *soap_tmp_ns2__validateUserResponse->_validateUserReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getDynaTuneInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ArrayOf_USCORExsd_USCOREstring *_params, struct ns2__getDynaTuneInfoResponse *_param_2)
{	struct ns2__getDynaTuneInfo soap_tmp_ns2__getDynaTuneInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8081/authws/services/AuthenticationService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__getDynaTuneInfo._params = _params;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__getDynaTuneInfo(soap, &soap_tmp_ns2__getDynaTuneInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__getDynaTuneInfo(soap, &soap_tmp_ns2__getDynaTuneInfo, "ns2:getDynaTuneInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__getDynaTuneInfo(soap, &soap_tmp_ns2__getDynaTuneInfo, "ns2:getDynaTuneInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns2__getDynaTuneInfoResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns2__getDynaTuneInfoResponse(soap, _param_2, "ns2:getDynaTuneInfoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__isUserValidated(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_nU, enum xsd__boolean *_isUserValidatedReturn)
{	struct ns2__isUserValidated soap_tmp_ns2__isUserValidated;
	struct ns2__isUserValidatedResponse *soap_tmp_ns2__isUserValidatedResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8081/authws/services/AuthenticationService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__isUserValidated._nU = _nU;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__isUserValidated(soap, &soap_tmp_ns2__isUserValidated);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__isUserValidated(soap, &soap_tmp_ns2__isUserValidated, "ns2:isUserValidated", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__isUserValidated(soap, &soap_tmp_ns2__isUserValidated, "ns2:isUserValidated", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_isUserValidatedReturn)
		return soap_closesock(soap);
	soap_default_xsd__boolean(soap, _isUserValidatedReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns2__isUserValidatedResponse = soap_get_ns2__isUserValidatedResponse(soap, NULL, "ns2:isUserValidatedResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_isUserValidatedReturn && soap_tmp_ns2__isUserValidatedResponse->_isUserValidatedReturn)
		*_isUserValidatedReturn = *soap_tmp_ns2__isUserValidatedResponse->_isUserValidatedReturn;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
